### PR TITLE
Use nanoids as Eids for schema-based hierarchy generation

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
*Issue #, if available:* #86

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cdisselkoen — CHANGES_REQUESTED** [review]
This looks great, I'm just requesting one change -- can we get a separate setting to control whether ids are generated via `Arbitrary` or `nanoid`, rather than reusing the setting for schema-based generation vs not?

**Review by aaronjeline — APPROVED** [review]
Just making sure I'm correct here: We don't actually care about the security properties of these IDs, we're just using them as an easy way to generate IDs right?

**Comment by shaobo-he-aws** [comment]
> 

Correct.

**Review by khieta — APPROVED** [review]

**Comment by khieta** [comment]
Approved, but I imagine you'll have to fix the CI break before merging.

**Review by cdisselkoen — APPROVED** [review]

**Review by andrewmwells-amazon — APPROVED** [review]

**Pull request merged**
