### PR TITLE
Pin batteries to 4.8.0

### PR DESCRIPTION
**Pull request by aaronjeline**
*Issue #, if available:*
N/A
*Description of changes:*
Updating batteries to latest

### CODE REVIEW

**Review by cdisselkoen — APPROVED** [review]
Looks like it's anchoring us to 4.8.0 rather than `main`, which is not an update per se, but I assume it is what we want?

**Review by khieta — COMMENTED** [review]
Based on https://github.com/leanprover-community/batteries/tags, it looks like the latest version is 4.9.1. Is there a reason we want 4.8.0?

**Comment by cdisselkoen** [comment]
We're currently on Lean 4.8; I assume we want to be on the matching version of Batteries?

Separately, we could update to Lean 4.9

**Review by khieta — APPROVED** [review]
Gotcha. I'll approve then.

**Pull request merged**
