### PR TITLE
Add a utility script for list and comparing lemma over the RU limit

### PR DESCRIPTION
**Pull request by john-h-kastner-aws**
A script I wrote to look at the lemmas over the resource unit threshold. Might be useful to keep with the repository.

### CODE REVIEW

**Comment by khieta** [comment]
I think you can do this (and other checks) using [dafny-reportgenerator](https://github.com/dafny-lang/dafny-reportgenerator/). I've been looking into this a little because I'd like to add something like this to the CI. Will keep you posted.

**Comment by shaobo-he-aws** [comment]
> I think you can do this (and other checks) using [dafny-reportgenerator](https://github.com/dafny-lang/dafny-reportgenerator/). I've been looking into this a little because I'd like to add something like this to the CI. Will keep you posted.

Thank you for sharing it. Should we merge this PR first and you can create another PR for dafny-reportgenerator?

**Comment by khieta** [comment]
How about, rather than merging this PR, we merge #52. It adds some basic instructions on measuring proof stability using `dafny-reportgenerator` to the README.

**Comment by khieta** [comment]
Made an issue to track the CI update (#53)

**Comment by shaobo-he-aws** [comment]
@john-h-kastner-aws are you OK with closing this PR and merge Kesha's instead?

**Pull request closed without merging**
